# Note the application is not complete, so most of these values are not being used
application:
    main_config:
        python_executable: "python3"
        n_python_workers: 32
        use_cuda: yes
        training_mode: yes
        preload:
            enabled: yes
            from: "/pretrained/model1.json"
            error_on_inconsistent_preload: yes
        save:
            enabled: yes
            to: "/user_data/checkpoints/"
            frequency: 120
        log:
            enabled: yes
            to: "/user_data/logs/"
            file_name_starts_with: "user_log"
    
    model:
        n_levels: 6
